### PR TITLE
add HumansState and modified BodyParts this messages are used in the kinect-server-node

### PR DESCRIPTION
**Pull request by Rbelder**
- HumansState has observed_user_ids for fast access to the actual observed users without looping the hole list of humans
- all Humans are in one message with Tf included

### CODE REVIEW

**Comment by airballking** [comment]
@Rbelder Thank you for the pull request! I have somes requests to improve your pull request:
* Could you please remove this line from ```HumanState.msg```: ```int32[] observed_user_ids ```? I think it is redundant with the slot ```userID``` from ```Human.msg```
* Could you please rename ```HumanState.msg``` into ```Humans.msg```?

If you don't mind, I will iterate over some of the slot fields after we have merged this and the actual perception node...

**Comment by Rbelder** [comment]
Indeed it is redundant, I put it there to have a overview of actual observed userID's. Otherwise the amount of Humans is hard to observe. I will do so and name HumansState.msg to Humans.msg.

**Comment by Rbelder** [comment]
The pull request is not processed but accepted right? I updated the CMakelist file which I forgot yesterday. So it would be in if the request is processed.

**Comment by airballking** [comment]
Merging so that we can start work on integrating human perception.

**Pull request merged**
